### ISSUE TITLE
change escape character

### ISSUE THREAD

**Issue by dbaid** [feiin/sqlstring#1]
Hello,

   Is there any way change the default escape character '\ 'into ''' ?
   After my testing with oracle + database/sql + github.com/sijms/go-ora,
   it seems that escape single quote with \' didn't work.
   I used ReplaceAll instead to solve the current single quote issue I met.

Regards,
Steven

**Comment by feiin** [comment]
Thank you for the information,  I'll  add this feature.

**Comment by feiin** [comment]
Hi @dbaid   you can use `sqlstring.SetSingleQuoteEscaper`  to change the default escape character \'
```
sqlstring.SetSingleQuoteEscaper("'")

sql := sqlstring.Format('.......',x,x)

```

**Comment by dbaid** [comment]
Thank you. It works.

Best Regards,
dbaid

**Comment by feiin** [comment]
@dbaid  You should update  the version v0.3.0 and replace `'` with `''`
```
sqlstring.SetSingleQuoteEscaper("''")
sql := sqlstring.Format(".......",x,x)

```

**Comment by dbaid** [comment]
@feiin 
      Thank you for your update.
      Here is an example of my code.
sqlstring.SetSingleQuoteEscaper("''")

sqlstring.Escape(contact.Address.String)

It works. No worry!!

Regards,
dbaid
